import { notFound } from "next/navigation";
import { getAdminPlace } from "@/lib/admin-api";
import { saveAttributeInfo, saveBasicInfo, saveServiceInfo } from "./actions";

interface Props { params: Promise<{ id: string }> }
const attributeLabels: Record<string, string> = { english_support: "영어 응대", korean_phone_required: "한국 전화번호 필요", international_phone_supported: "해외 전화번호 지원", foreign_card: "해외 카드", same_day_booking: "당일 예약 문의", walk_in: "워크인", solo_friendly: "1인 방문", price_confirmed: "가격 확인" };

export default async function AdminPlaceDetailPage({ params }: Props) {
  const place = await getAdminPlace((await params).id); if (!place) notFound(); const service = place.place_services[0]; const attributes = new Map(place.place_attributes.map((item) => [item.attribute_type, item]));
  return <div className="grid"><div><h1>{place.name_ko}</h1><p className="muted">장소 정보·가격·검증 속성을 직접 수정합니다. 저장 내용은 작업 이력에 남습니다.</p></div>
    <section className="panel"><h2>기본 정보</h2><form action={saveBasicInfo} className="admin-form"><input type="hidden" name="placeId" value={place.id} /><label>한글 이름<input className="input" name="nameKo" defaultValue={place.name_ko} required /></label><label>영문 이름<input className="input" name="nameEn" defaultValue={place.name_en ?? ""} /></label><label>업종<select className="input" name="category" defaultValue={place.primary_category}><option value="hair">헤어</option><option value="nails">네일</option><option value="head_spa">헤드스파</option><option value="personal_color">퍼스널컬러</option></select></label><label>지역<select className="input" name="area" defaultValue={place.area}><option value="hongdae">홍대</option><option value="myeongdong">명동</option><option value="gangnam">강남</option><option value="seongsu">성수</option></select></label><label className="wide">주소<input className="input" name="address" defaultValue={place.address_ko ?? ""} /></label><label>전화번호<input className="input" name="phone" defaultValue={place.phone ?? ""} /></label><label>공식 홈페이지<input className="input" type="url" name="website" defaultValue={place.official_website ?? ""} /></label><div className="wide"><button className="button">기본 정보 저장</button></div></form></section>
    <section className="panel"><h2>가격과 소요 시간</h2><form action={saveServiceInfo} className="admin-form"><input type="hidden" name="placeId" value={place.id} /><label>최소 가격<input className="input" type="number" min="0" name="minPrice" defaultValue={service?.min_price ?? ""} /></label><label>최대 가격<input className="input" type="number" min="0" name="maxPrice" defaultValue={service?.max_price ?? ""} /></label><label>최소 소요 시간(분)<input className="input" type="number" min="0" name="durationMin" defaultValue={service?.duration_min ?? ""} /></label><label>최대 소요 시간(분)<input className="input" type="number" min="0" name="durationMax" defaultValue={service?.duration_max ?? ""} /></label><label className="wide">가격 참고사항<textarea className="input" name="priceNote" defaultValue={service?.price_note ?? ""} /></label><div className="wide"><button className="button">가격 정보 저장</button></div></form></section>
    <section className="panel"><h2>검증 속성</h2><p className="muted">미확인을 저장하면 기존 속성이 삭제됩니다. 확인된 정보만 true/false로 저장하세요.</p><div className="attribute-editor">{Object.entries(attributeLabels).map(([type, label]) => { const current = attributes.get(type); const value = current?.value_json?.value; return <form action={saveAttributeInfo} key={type}><input type="hidden" name="placeId" value={place.id} /><input type="hidden" name="type" value={type} /><strong>{label}</strong><select className="input" name="value" defaultValue={value === true ? "true" : value === false ? "false" : "unknown"}><option value="unknown">미확인</option><option value="true">가능·지원</option><option value="false">불가·미지원</option></select><select className="input" name="verificationStatus" defaultValue={current?.verification_status ?? "business_confirmed"}><option value="business_confirmed">업체 직접 확인</option><option value="official_source">공식 출처</option><option value="visitor_confirmed">방문자 확인</option><option value="likely">추정</option></select><input className="input" name="evidence" defaultValue={current?.evidence_text ?? ""} placeholder="확인 근거 또는 메모" /><button className="button secondary">저장</button></form>; })}</div></section>
    <section className="panel"><h2>출처 {place.sources.length}건</h2><table><thead><tr><th>종류</th><th>URL</th><th>확인일</th></tr></thead><tbody>{place.sources.map((source) => <tr key={source.id}><td>{source.source_type}</td><td>{source.source_url ? <a href={source.source_url} target="_blank" rel="noreferrer">{source.title ?? source.source_url}</a> : "-"}</td><td>{new Date(source.checked_at).toLocaleDateString("ko-KR")}</td></tr>)}</tbody></table></section>
  </div>;
}
