import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { BookingMessageGenerator } from "@/components/booking/booking-message-generator";
import { getPublicPlace } from "@/lib/public-api";
import { attributeLabel, humanValue, verificationPresentation } from "@/lib/presentation";
import { ChangeReportForm } from "@/components/change-report-form";
import { PlaceMap } from "@/components/place-map";

interface Props { params: Promise<{ slug: string }> }
const labels: Record<string, string> = { hongdae: "홍대", myeongdong: "명동", gangnam: "강남", seongsu: "성수", hair: "헤어", nails: "네일", head_spa: "헤드스파", personal_color: "퍼스널컬러" };
const attributeLabels: Record<string, string> = { english_support: "영어 응대", korean_phone_required: "한국 전화번호", international_phone_supported: "해외 전화번호", foreign_card: "해외 발급 카드", same_day_booking: "당일 예약 문의", walk_in: "워크인", solo_friendly: "1인 방문", price_confirmed: "가격 정보" };
const statusLabels: Record<string, string> = { verified: "근거 확인", likely: "가능성 높음 — 방문 전 재확인", unknown: "확인되지 않음", outdated: "오래된 정보 — 재확인 필요" };
const valueKo = (type: string, value: unknown) => type === "korean_phone_required" ? (value === false ? "필요하지 않음" : value === true ? "필요함" : "미확인") : typeof value === "boolean" ? (value ? "지원" : "지원하지 않음") : humanValue(type, value);
const money = (value: number | null) => value === null ? null : `${value.toLocaleString("ko-KR")}원`;

export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const slug = (await params).slug; const place = await getPublicPlace(slug); if (!place) return { title: "장소를 찾을 수 없습니다 | K-Beauty Now" };
  return { title: `${place.nameKo} — 예약·가격·외국인 이용 안내 | K-Beauty Now`, description: `${place.nameKo}의 예약 조건, 가격, 영어 응대와 외국인 이용 정보를 확인하세요.`, alternates: { canonical: `/ko/places/${slug}`, languages: { en: `/en/places/${slug}`, ko: `/ko/places/${slug}`, "x-default": `/en/places/${slug}` } } };
}

export default async function KoreanPlacePage({ params }: Props) {
  const place = await getPublicPlace((await params).slug); if (!place) notFound(); const service = place.services[0]; const officialHref = place.bookingChannels.website;
  return <main className="place-detail-page"><nav className="breadcrumbs"><Link href="/ko">홈</Link><span>›</span><Link href={`/ko/search?area=${place.area}&category=${place.category}`}>{labels[place.area]}</Link><span>›</span><span>{place.nameKo}</span></nav><section className="detail-hero"><div><span className="place-kicker">{labels[place.area]} · {labels[place.category]}</span><h1>{place.nameKo}</h1>{place.nameEn && <p className="local-name">{place.nameEn}</p>}<p className="detail-address">{place.address ?? "주소 확인 중"}</p></div><div className="detail-trust"><span className="verified-dot">서울 뷰티 가이드</span></div></section><div className="detail-layout"><div className="detail-content">
    {place.coordinates && <section className="decision-panel"><span className="eyebrow">위치</span><h2>방문 전에 위치 확인하기</h2><PlaceMap name={place.nameKo} address={place.address ?? `${labels[place.area]}, 서울`} latitude={place.coordinates.latitude} longitude={place.coordinates.longitude} locale="ko" apiKey={process.env.NEXT_PUBLIC_KAKAO_MAP_JAVASCRIPT_KEY ?? ""} /></section>}
    <section className="decision-panel"><span className="eyebrow">빠른 판단</span><h2>외국인 방문객이 실제로 이용할 수 있을까요?</h2><div className="decision-grid">{place.attributeDetails.length ? place.attributeDetails.slice(0, 6).map((attribute) => { const status = verificationPresentation(attribute.verificationStatus, attribute.expiresAt); return <article key={attribute.type} className={`decision-item ${status.tone}`}><span className="status-symbol">{status.tone === "verified" ? "✓" : status.tone === "likely" ? "~" : "?"}</span><div><h3>{attributeLabels[attribute.type] ?? attributeLabel(attribute.type)}</h3><strong>{valueKo(attribute.type, attribute.value)}</strong><p>{statusLabels[status.tone]}</p>{attribute.verifiedAt && <small>{new Date(attribute.verifiedAt).toLocaleDateString("ko-KR")} 확인</small>}</div></article>; }) : <div className="detail-empty">예약 조건이 아직 확인되지 않았습니다. 방문 전에 업체에 직접 문의해 주세요.</div>}</div></section>
    <section className="detail-section"><span className="eyebrow">서비스</span><h2>가격과 소요 시간</h2>{place.services.length ? <div className="service-list">{place.services.map((item) => <article key={item.code}><div><h3>{labels[item.code] ?? item.name}</h3>{item.priceNote && <p>{item.priceNote}</p>}</div><div><strong>{[money(item.minPrice), money(item.maxPrice)].filter(Boolean).join(" – ") || "가격 문의"}</strong><span>{item.durationMin ? `${item.durationMin}${item.durationMax ? `–${item.durationMax}` : ""}분` : "소요 시간 미확인"}</span></div></article>)}</div> : <div className="detail-empty">가격이 확인되지 않았습니다. 예약 전에 견적을 문의해 주세요.</div>}</section>
    <section className="detail-section"><span className="eyebrow">문의 방법</span><h2>업체에 직접 확인하세요</h2><div className="booking-steps"><div><span>1</span><p>업체의 공식 홈페이지를 확인합니다.</p></div><div><span>2</span><p>원하는 시술과 시간을 정합니다.</p></div><div><span>3</span><p>아래 메시지를 복사해 업체에 문의합니다.</p></div></div><div className="booking-links">{place.bookingChannels.website && <a className="button secondary" href={place.bookingChannels.website} target="_blank" rel="noreferrer">공식 홈페이지 ↗</a>}{place.bookingChannels.phone && <a className="button secondary" href={`tel:${place.bookingChannels.phone}`}>전화 {place.bookingChannels.phone}</a>}{!officialHref && !place.bookingChannels.phone && <span className="notice">확인된 공식 연락 경로가 없습니다.</span>}</div></section>
    <section className="detail-section" id="message"><span className="eyebrow">문의 메시지</span><h2>언어 걱정 없이 예약 문의하기</h2><p className="section-copy">아는 정보만 입력한 뒤 영어 또는 한국어 메시지를 예약 채널에 붙여 넣으세요.</p><BookingMessageGenerator placeName={place.nameKo} defaultService={labels[place.category] ?? "뷰티 시술"} locale="ko" /></section>
    {(place.menuItems.length > 0 || place.openingHours || place.socialAccounts.length > 0) && <section className="detail-section"><span className="eyebrow">확인된 정보</span><h2>메뉴·영업시간·공식 채널</h2>{place.openingHours && <p><strong>영업시간:</strong> {place.openingHours.text}</p>}{place.socialAccounts.length > 0 && <div className="booking-links">{place.socialAccounts.map((account) => <a className="button" href={account.url} target="_blank" rel="noreferrer" key={`${account.platform}-${account.url}`}>{account.platform === "instagram" ? `Instagram${account.handle ? ` @${account.handle}` : ""}` : account.platform} ↗</a>)}</div>}{place.menuItems.length > 0 && <div className="service-list">{place.menuItems.map((item) => <article key={item.id}><div><h3>{item.name}</h3></div><div><strong>{item.price.toLocaleString("ko-KR")}원</strong><span>{new Date(item.checkedAt).toLocaleDateString("ko-KR")} 확인</span></div></article>)}</div>}</section>}
    <ChangeReportForm placeId={place.id} slug={place.slug} locale="ko" />
  </div><aside className="booking-card"><span className="eyebrow">업체에 문의하기</span><h2>{service ? [money(service.minPrice), money(service.maxPrice)].filter(Boolean).join(" – ") || "가격 문의" : "가격 문의"}</h2><p>{service?.durationMin ? `${service.durationMin}${service.durationMax ? `–${service.durationMax}` : ""}분` : "소요 시간 미확인"}</p><div className="booking-card-facts"><span><b>{officialHref ? "✓" : "?"}</b> 공식 홈페이지</span><span><b>{place.attributes.english_support ? "✓" : "?"}</b> 영어 응대</span><span><b>{place.attributes.korean_phone_required === false ? "✓" : "?"}</b> 한국 전화번호 불필요</span></div>{officialHref ? <a className="search-cta" href={officialHref} target="_blank" rel="noreferrer">공식 홈페이지 <span>→</span></a> : <a className="search-cta" href="#message">문의 메시지 준비 <span>↓</span></a>}<small>외부 페이지의 예약 기능은 보장하지 않습니다. 예약 방법은 업체에 직접 확인해 주세요.</small></aside></div><div className="mobile-booking-bar"><span><strong>{place.nameKo}</strong><small>{service ? money(service.minPrice) ?? "가격 문의" : "가격 문의"}</small></span>{officialHref ? <a href={officialHref} target="_blank" rel="noreferrer">공식 홈페이지</a> : <a href="#message">문의하기</a>}</div></main>;
}
